# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import emergency_pb2 as emergency__pb2


class EmergencyServiceStub(object):
    """Service de gestion des urgences
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetVehicle = channel.unary_unary(
                '/emergency.EmergencyService/GetVehicle',
                request_serializer=emergency__pb2.VehicleRequest.SerializeToString,
                response_deserializer=emergency__pb2.Vehicle.FromString,
                )
        self.GetAllVehicles = channel.unary_unary(
                '/emergency.EmergencyService/GetAllVehicles',
                request_serializer=emergency__pb2.Empty.SerializeToString,
                response_deserializer=emergency__pb2.VehicleList.FromString,
                )
        self.GetAvailableVehicles = channel.unary_unary(
                '/emergency.EmergencyService/GetAvailableVehicles',
                request_serializer=emergency__pb2.VehicleTypeRequest.SerializeToString,
                response_deserializer=emergency__pb2.VehicleList.FromString,
                )
        self.CreateVehicle = channel.unary_unary(
                '/emergency.EmergencyService/CreateVehicle',
                request_serializer=emergency__pb2.VehicleInput.SerializeToString,
                response_deserializer=emergency__pb2.Vehicle.FromString,
                )
        self.UpdateVehicleStatus = channel.unary_unary(
                '/emergency.EmergencyService/UpdateVehicleStatus',
                request_serializer=emergency__pb2.StatusUpdate.SerializeToString,
                response_deserializer=emergency__pb2.Vehicle.FromString,
                )
        self.CreateIntervention = channel.unary_unary(
                '/emergency.EmergencyService/CreateIntervention',
                request_serializer=emergency__pb2.InterventionInput.SerializeToString,
                response_deserializer=emergency__pb2.Intervention.FromString,
                )
        self.GetActiveInterventions = channel.unary_unary(
                '/emergency.EmergencyService/GetActiveInterventions',
                request_serializer=emergency__pb2.Empty.SerializeToString,
                response_deserializer=emergency__pb2.InterventionList.FromString,
                )
        self.CompleteIntervention = channel.unary_unary(
                '/emergency.EmergencyService/CompleteIntervention',
                request_serializer=emergency__pb2.InterventionRequest.SerializeToString,
                response_deserializer=emergency__pb2.Intervention.FromString,
                )


class EmergencyServiceServicer(object):
    """Service de gestion des urgences
    """

    def GetVehicle(self, request, context):
        """Récupérer un véhicule par ID
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllVehicles(self, request, context):
        """Récupérer tous les véhicules
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAvailableVehicles(self, request, context):
        """Récupérer les véhicules disponibles par type
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateVehicle(self, request, context):
        """Créer un nouveau véhicule
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateVehicleStatus(self, request, context):
        """Mettre à jour le statut d'un véhicule
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateIntervention(self, request, context):
        """Créer une intervention
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetActiveInterventions(self, request, context):
        """Récupérer les interventions actives
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CompleteIntervention(self, request, context):
        """Terminer une intervention
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EmergencyServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetVehicle': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVehicle,
                    request_deserializer=emergency__pb2.VehicleRequest.FromString,
                    response_serializer=emergency__pb2.Vehicle.SerializeToString,
            ),
            'GetAllVehicles': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllVehicles,
                    request_deserializer=emergency__pb2.Empty.FromString,
                    response_serializer=emergency__pb2.VehicleList.SerializeToString,
            ),
            'GetAvailableVehicles': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAvailableVehicles,
                    request_deserializer=emergency__pb2.VehicleTypeRequest.FromString,
                    response_serializer=emergency__pb2.VehicleList.SerializeToString,
            ),
            'CreateVehicle': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateVehicle,
                    request_deserializer=emergency__pb2.VehicleInput.FromString,
                    response_serializer=emergency__pb2.Vehicle.SerializeToString,
            ),
            'UpdateVehicleStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateVehicleStatus,
                    request_deserializer=emergency__pb2.StatusUpdate.FromString,
                    response_serializer=emergency__pb2.Vehicle.SerializeToString,
            ),
            'CreateIntervention': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateIntervention,
                    request_deserializer=emergency__pb2.InterventionInput.FromString,
                    response_serializer=emergency__pb2.Intervention.SerializeToString,
            ),
            'GetActiveInterventions': grpc.unary_unary_rpc_method_handler(
                    servicer.GetActiveInterventions,
                    request_deserializer=emergency__pb2.Empty.FromString,
                    response_serializer=emergency__pb2.InterventionList.SerializeToString,
            ),
            'CompleteIntervention': grpc.unary_unary_rpc_method_handler(
                    servicer.CompleteIntervention,
                    request_deserializer=emergency__pb2.InterventionRequest.FromString,
                    response_serializer=emergency__pb2.Intervention.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'emergency.EmergencyService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class EmergencyService(object):
    """Service de gestion des urgences
    """

    @staticmethod
    def GetVehicle(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/emergency.EmergencyService/GetVehicle',
            emergency__pb2.VehicleRequest.SerializeToString,
            emergency__pb2.Vehicle.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAllVehicles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/emergency.EmergencyService/GetAllVehicles',
            emergency__pb2.Empty.SerializeToString,
            emergency__pb2.VehicleList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAvailableVehicles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/emergency.EmergencyService/GetAvailableVehicles',
            emergency__pb2.VehicleTypeRequest.SerializeToString,
            emergency__pb2.VehicleList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateVehicle(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/emergency.EmergencyService/CreateVehicle',
            emergency__pb2.VehicleInput.SerializeToString,
            emergency__pb2.Vehicle.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateVehicleStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/emergency.EmergencyService/UpdateVehicleStatus',
            emergency__pb2.StatusUpdate.SerializeToString,
            emergency__pb2.Vehicle.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateIntervention(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/emergency.EmergencyService/CreateIntervention',
            emergency__pb2.InterventionInput.SerializeToString,
            emergency__pb2.Intervention.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetActiveInterventions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/emergency.EmergencyService/GetActiveInterventions',
            emergency__pb2.Empty.SerializeToString,
            emergency__pb2.InterventionList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CompleteIntervention(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/emergency.EmergencyService/CompleteIntervention',
            emergency__pb2.InterventionRequest.SerializeToString,
            emergency__pb2.Intervention.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
